CREATE TABLE Series (id INTEGER PRIMARY KEY, title TEXT, author_id INTEGER, subgenre_id INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY KEY);
CREATE TABLE Series (id INTEGER PRIMARY KEY);
CREATE TABLE Series (id INTEGER PRIMARY KEY);
CREATE TABLE Series (id INTEGER PRIMARY KEY);