CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);