CREATE TABLE Series (id INTEGER PRIMARY INTEGER, title TEXT, author_id INTEGER, sub_genre_id INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);
CREATE TABLE Series (id INTEGER PRIMARY INTEGER);